#WAP TO PRINT THE USER DEFINE FUNCTION IN PYTHON AND USER INPUT .

def add(a,b):
    return a+b
def sub(a,b):
    return a-b
def mul(a,b):
    return a*b
def div(a,b):
    return a/b
def mod(a,b):
    return
def main():
    a=int(input("Enter the first number:"))
    b=int(input("Enter the second number:"))
    print("Addition of two number is:",add(a,b))
    print("Subtraction of two number is:",sub(a,b))
    print("Multiplication of two number is:",mul(a,b))
    print("Division of two number is:",div(a,b))
    print("Modulus of two number is:",mod(a,b))
main()





